version: 2
updates:
  - package-ecosystem: "pip"
    directory: "requirements"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    pull-request-branch-name:
      separator: _
  - package-ecosystem: "pip"
    directory: "egg"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: _
